version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=store
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5002:80"

  proxy:
    build: ./proxy
    container_name: proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  db_data: